class MockDataSearched {
  static final mocksSearchedJson = {
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
        "genre_ids": [28, 12, 14, 878],
        "id": 19995,
        "original_language": "en",
        "original_title": "Avatar",
        "overview":
            "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
        "popularity": 1009.779,
        "poster_path": "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
        "release_date": "2009-12-15",
        "title": "Avatar",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 28181
      },
      {
        "adult": false,
        "backdrop_path": "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
        "genre_ids": [878, 12, 28],
        "id": 76600,
        "original_language": "en",
        "original_title": "Avatar: The Way of Water",
        "overview":
            "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        "popularity": 1954.665,
        "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        "release_date": "2022-12-14",
        "title": "Avatar: The Way of Water",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 4990
      },
      {
        "adult": false,
        "backdrop_path": "/uEwGFGtao9YG2JolmdvtHLLVbA9.jpg",
        "genre_ids": [99],
        "id": 111332,
        "original_language": "en",
        "original_title": "Avatar: Creating the World of Pandora",
        "overview":
            "The Making-of James Cameron's Avatar. It shows interesting parts of the work on the set.",
        "popularity": 281.002,
        "poster_path": "/d9oqcfeCyc3zmMal6eJbfj3gatc.jpg",
        "release_date": "2010-02-07",
        "title": "Avatar: Creating the World of Pandora",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 40
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99],
        "id": 287003,
        "original_language": "en",
        "original_title": "Avatar: Scene Deconstruction",
        "overview": "The deconstruction of the Avatar scenes and sets",
        "popularity": 205.038,
        "poster_path": "/uCreCQFReeF0RiIXkQypRYHwikx.jpg",
        "release_date": "2009-12-18",
        "title": "Avatar: Scene Deconstruction",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 13
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [28, 878, 12, 14],
        "id": 216527,
        "original_language": "en",
        "original_title": "Avatar 4",
        "overview": "",
        "popularity": 85.418,
        "poster_path": "/qzMYKnT4MG1d0gnhwytr4cKhUvS.jpg",
        "release_date": "2026-12-16",
        "title": "Avatar 4",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [28, 18, 878, 12, 14],
        "id": 83533,
        "original_language": "en",
        "original_title": "Avatar 3",
        "overview": "",
        "popularity": 75.327,
        "poster_path": "/4rXqTMlkEaMiJjiG0Z2BX6F6Dkm.jpg",
        "release_date": "2024-12-18",
        "title": "Avatar 3",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [28, 12, 14, 878],
        "id": 393209,
        "original_language": "en",
        "original_title": "Avatar 5",
        "overview": "",
        "popularity": 71.676,
        "poster_path": "/rtmmvqkIC5zDMEd638Es2woxbz8.jpg",
        "release_date": "2028-12-20",
        "title": "Avatar 5",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/nNceJtrrovG1MUBHMAhId0ws9Gp.jpg",
        "genre_ids": [99],
        "id": 183392,
        "original_language": "en",
        "original_title": "Capturing Avatar",
        "overview":
            "Capturing Avatar is a feature length behind-the-scenes documentary about the making of Avatar. It uses footage from the film's development, as well as stock footage from as far back as the production of Titanic in 1995. Also included are numerous interviews with cast, artists, and other crew members. The documentary was released as a bonus feature on the extended collector's edition of Avatar.",
        "popularity": 52.234,
        "poster_path": "/26SMEXJl3978dn2svWBSqHbLl5U.jpg",
        "release_date": "2010-11-16",
        "title": "Capturing Avatar",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 41
      },
      {
        "adult": false,
        "backdrop_path": "/eoAvHxfbaPOcfiQyjqypWIXWxDr.jpg",
        "genre_ids": [99],
        "id": 1059673,
        "original_language": "en",
        "original_title": "Avatar: The Deep Dive - A Special Edition of 20/20",
        "overview":
            "An inside look at one of the most anticipated movie sequels ever with James Cameron and cast.",
        "popularity": 305.231,
        "poster_path": "/rtVeIsmeXnpjNbEKnm9Say58XjV.jpg",
        "release_date": "2022-12-14",
        "title": "Avatar: The Deep Dive - A Special Edition of 20/20",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 15
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99],
        "id": 278698,
        "original_language": "en",
        "original_title": "Avatar Spirits",
        "overview":
            "Bryan Konietzko and Michael Dante DiMartino, co-creators of the hit television series, Avatar: The Last Airbender, reflect on the creation of the masterful series.",
        "popularity": 27.506,
        "poster_path": "/oBWVyOdntLJd5bBpE0wkpN6B6vy.jpg",
        "release_date": "2010-06-22",
        "title": "Avatar Spirits",
        "video": false,
        "vote_average": 9,
        "vote_count": 16
      },
      {
        "adult": false,
        "backdrop_path": "/cACUWJKvRfhXge7NC0xxoQnkQNu.jpg",
        "genre_ids": [10402],
        "id": 993545,
        "original_language": "fr",
        "original_title": "Avatar - Au Hellfest 2022",
        "overview": "",
        "popularity": 16.833,
        "poster_path": "/fw6cPIsQYKjd1YVQanG2vLc5HGo.jpg",
        "release_date": "2022-06-26",
        "title": "Avatar - Au Hellfest 2022",
        "video": false,
        "vote_average": 8,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 931019,
        "original_language": "en",
        "original_title": "Avatar: Enter The World",
        "overview":
            "A behind the scenes look at the new James Cameron blockbuster “Avatar”, which stars Aussie Sam Worthington. Hastily produced by Australia’s Nine Network following the film’s release.",
        "popularity": 10.889,
        "poster_path": "/9MHY9pYAgs91Ef7YFGWEbP4WJqC.jpg",
        "release_date": "2009-12-05",
        "title": "Avatar: Enter The World",
        "video": false,
        "vote_average": 2,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": "/x43RWEZg9tYRPgnm43GyIB4tlER.jpg",
        "genre_ids": [],
        "id": 740017,
        "original_language": "es",
        "original_title": "Avatar: Agni Kai",
        "overview": "",
        "popularity": 4.373,
        "poster_path": "/y9PrKMUTA6NfIe5FE92tdwOQ2sH.jpg",
        "release_date": "2020-01-18",
        "title": "Avatar: Agni Kai",
        "video": false,
        "vote_average": 7,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": "/e8mmDO7fKK93T4lnxl4Z2zjxXZV.jpg",
        "genre_ids": [12, 18, 14],
        "id": 668297,
        "original_language": "en",
        "original_title": "The Last Avatar",
        "overview":
            "A young man leaves Hollywood to find himself. What he finds is beyond his wildest imagination.",
        "popularity": 5.482,
        "poster_path": "/XWz5SS5g5mrNEZjv3FiGhqCMOQ.jpg",
        "release_date": "2014-12-06",
        "title": "The Last Avatar",
        "video": false,
        "vote_average": 4.5,
        "vote_count": 2
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 424768,
        "original_language": "en",
        "original_title": "Avatar:[2015] Wacken Open Air",
        "overview":
            "Started in the summer of 2001 by drummer John Alfredsson and vocalist Christian Rimmi under the name Lost Soul.  The band offers a free mp3 download to a song called \"Bloody Knuckles\" if one subscribes to their newsletter.  In 2005 they appeared on the compilation “Listen to Your Inner Voice” together with 17 other bands released by Inner Voice Records.",
        "popularity": 6.281,
        "poster_path": null,
        "release_date": "2015-08-01",
        "title": "Avatar:[2015] Wacken Open Air",
        "video": false,
        "vote_average": 8,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 287004,
        "original_language": "en",
        "original_title": "Avatar: Production Materials",
        "overview": "Production material overview of what was used in Avatar",
        "popularity": 3.706,
        "poster_path": null,
        "release_date": "2009-12-18",
        "title": "Avatar: Production Materials",
        "video": true,
        "vote_average": 6,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [],
        "id": 812836,
        "original_language": "en",
        "original_title": "Avatar - Live At Graspop 2018",
        "overview": "Live At Graspop Festival Belgium 2018",
        "popularity": 3.664,
        "poster_path": null,
        "release_date": "",
        "title": "Avatar - Live At Graspop 2018",
        "video": false,
        "vote_average": 9,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [99, 878],
        "id": 100287,
        "original_language": "da",
        "original_title": "Min Avatar og mig",
        "overview":
            "is a creative documentary-fiction film and a film that might expand your sense of reality. It is the story about a man who enters the virtual world Second Life to pursue his personal dreams and ambitions. His journey into cyberspace becomes a magic learning experience, which gradually opens the gates to a much larger reality.",
        "popularity": 1.129,
        "poster_path": "/dZCj0jiOoDzAzbQM7ryYFEjkjs7.jpg",
        "release_date": "2010-11-10",
        "title": "My Avatar and Me",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [10402],
        "id": 874770,
        "original_language": "en",
        "original_title": "Avatar Ages: Memories",
        "overview":
            "On the night of memories Avatar performed songs from Thoughts of No Tomorrow, Schlacht and Avatar as voted on by the fans.",
        "popularity": 1.287,
        "poster_path": "/xDNNQ2cnxAv3o7u0nT6JJacQrhp.jpg",
        "release_date": "2021-01-30",
        "title": "Avatar Ages: Memories",
        "video": false,
        "vote_average": 10,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [10402],
        "id": 874768,
        "original_language": "en",
        "original_title": "Avatar Ages: Madness",
        "overview":
            "On the night of madness Avatar performed songs from Black Waltz and Hail The Apocalypse as voted on by the fans.",
        "popularity": 1.225,
        "poster_path": "/wVyTuruUctV3UbdzE5cncnpyNoY.jpg",
        "release_date": "2021-01-23",
        "title": "Avatar Ages: Madness",
        "video": false,
        "vote_average": 8,
        "vote_count": 1
      }
    ],
    "total_pages": 3,
    "total_results": 57
  };
}
